version: 2

project_name: mw-cli

builds:
  - id: mw-cli
    main: ./main.go
    binary: mw-cli

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - "7"

    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

    env:
      - CGO_ENABLED=0

    ldflags:
      - -s -w

archives:
  - id: mw-cli
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: ahacop
    name: mw-cli
  draft: false
  prerelease: auto
  mode: replace

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
